#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do
  echo
  echo ">>> running $installer"
  if ! sh -c "${installer}" ; then
    echo ">>> errors while running $installer"
  fi
done
